package com.problems.demo.relations.model;

public class IcRelations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_relations.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_relations.related_case_id
     *
     * @mbggenerated
     */
    private Integer relatedCaseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_relations.id
     *
     * @return the value of ic_relations.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_relations.id
     *
     * @param id the value for ic_relations.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_relations.related_case_id
     *
     * @return the value of ic_relations.related_case_id
     *
     * @mbggenerated
     */
    public Integer getRelatedCaseId() {
        return relatedCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_relations.related_case_id
     *
     * @param relatedCaseId the value for ic_relations.related_case_id
     *
     * @mbggenerated
     */
    public void setRelatedCaseId(Integer relatedCaseId) {
        this.relatedCaseId = relatedCaseId;
    }
}