package com.problems.demo.relations.dao;

import com.problems.demo.relations.model.IcRelations;
import com.problems.demo.relations.model.IcRelationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcRelationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    int countByExample(IcRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    int deleteByExample(IcRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    int insert(IcRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    int insertSelective(IcRelations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    List<IcRelations> selectByExample(IcRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IcRelations record, @Param("example") IcRelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_relations
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IcRelations record, @Param("example") IcRelationsExample example);
}