package com.problems.demo.case_type.model;

public class IcCaseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_case_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_case_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_case_type.parent_type_id
     *
     * @mbggenerated
     */
    private Integer parentTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_case_type.id
     *
     * @return the value of ic_case_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_case_type.id
     *
     * @param id the value for ic_case_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_case_type.type_name
     *
     * @return the value of ic_case_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_case_type.type_name
     *
     * @param typeName the value for ic_case_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_case_type.parent_type_id
     *
     * @return the value of ic_case_type.parent_type_id
     *
     * @mbggenerated
     */
    public Integer getParentTypeId() {
        return parentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_case_type.parent_type_id
     *
     * @param parentTypeId the value for ic_case_type.parent_type_id
     *
     * @mbggenerated
     */
    public void setParentTypeId(Integer parentTypeId) {
        this.parentTypeId = parentTypeId;
    }
}