package com.problems.demo.case_type.dao;

import com.problems.demo.case_type.model.IcCaseType;
import com.problems.demo.case_type.model.IcCaseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IcCaseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int countByExample(IcCaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int deleteByExample(IcCaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int insert(IcCaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int insertSelective(IcCaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    List<IcCaseType> selectByExample(IcCaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    IcCaseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IcCaseType record, @Param("example") IcCaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IcCaseType record, @Param("example") IcCaseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IcCaseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_case_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IcCaseType record);
}